// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOFeDmXoXidgvIdF_Wf7Z24LOtsZhSjw',
    appId: '1:349726579250:web:fc5956e8e2b6c7d790ba2b',
    messagingSenderId: '349726579250',
    projectId: 'medify-67e12',
    authDomain: 'medify-67e12.firebaseapp.com',
    storageBucket: 'medify-67e12.firebasestorage.app',
    measurementId: 'G-1SCDEM378E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbzXVc8w_775umoPLQvixIcvfxBV_jy6w',
    appId: '1:349726579250:android:095729644986901190ba2b',
    messagingSenderId: '349726579250',
    projectId: 'medify-67e12',
    storageBucket: 'medify-67e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwpKXC3XygqUQg6xk0ch8S1JuIVewD6xY',
    appId: '1:349726579250:ios:8f763e3ce9542d6190ba2b',
    messagingSenderId: '349726579250',
    projectId: 'medify-67e12',
    storageBucket: 'medify-67e12.firebasestorage.app',
    iosBundleId: 'com.medify.medify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwpKXC3XygqUQg6xk0ch8S1JuIVewD6xY',
    appId: '1:349726579250:ios:8f763e3ce9542d6190ba2b',
    messagingSenderId: '349726579250',
    projectId: 'medify-67e12',
    storageBucket: 'medify-67e12.firebasestorage.app',
    iosBundleId: 'com.medify.medify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrOFeDmXoXidgvIdF_Wf7Z24LOtsZhSjw',
    appId: '1:349726579250:web:582f48070e74273690ba2b',
    messagingSenderId: '349726579250',
    projectId: 'medify-67e12',
    authDomain: 'medify-67e12.firebaseapp.com',
    storageBucket: 'medify-67e12.firebasestorage.app',
    measurementId: 'G-8NPEX1M4XB',
  );
}
